export const resources = [
  "companies",
  "business_groups",
  "country_company_profiles",
  "branches",
  "countries",
  "country_branches",
  "city_branches",
  "clearing_agents",
  "clearing_agent_branches",
  "users",
  "roles",
  "accounts",
  "journal_entries",
  "ledger",
  "ledgers",
  "roznamcha",
  "transactions",
  "purchases",
  "sales",
  "bookings",
  "customers",
  "banks",
  "warehouses",
  "currency_rates",
  "reports",
  "global_reports",
  "assignments",
  "record_transfers",
  "inter_branch_transfers",
  "messages",
  "shipping_records",
  "attachments",
  "settings",
  "audit_logs"
] as const;

export const actions = ["create", "read", "update", "delete", "post", "approve", "export"] as const;

export type Resource = (typeof resources)[number];
export type PermissionAction = (typeof actions)[number];

export type Permission = `${Resource}:${PermissionAction}`;

export const systemRoles = {
  superAdmin: [
    "companies:read",
    "business_groups:create",
    "business_groups:read",
    "business_groups:update",
    "country_company_profiles:create",
    "country_company_profiles:read",
    "country_company_profiles:update",
    "branches:read",
    "countries:create",
    "countries:read",
    "countries:update",
    "country_branches:create",
    "country_branches:read",
    "country_branches:update",
    "city_branches:create",
    "city_branches:read",
    "city_branches:update",
    "users:read",
    "users:update",
    "roles:read",
    "roles:update",
    "transactions:read",
    "currency_rates:create",
    "currency_rates:read",
    "reports:read",
    "reports:approve",
    "reports:export",
    "global_reports:read",
    "global_reports:export",
    "clearing_agents:create",
    "clearing_agents:read",
    "clearing_agents:update",
    "clearing_agent_branches:create",
    "clearing_agent_branches:read",
    "clearing_agent_branches:update",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "record_transfers:approve",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "inter_branch_transfers:update",
    "inter_branch_transfers:approve",
    "messages:create",
    "messages:read",
    "settings:read",
    "settings:update",
    "audit_logs:read"
  ],
  countryAdmin: [
    "countries:read",
    "business_groups:read",
    "country_company_profiles:read",
    "country_branches:read",
    "city_branches:create",
    "city_branches:read",
    "city_branches:update",
    "users:read",
    "users:update",
    "transactions:read",
    "currency_rates:create",
    "currency_rates:read",
    "reports:read",
    "reports:export",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "inter_branch_transfers:approve",
    "messages:create",
    "messages:read"
  ],
  branchAdmin: [
    "countries:read",
    "business_groups:read",
    "country_company_profiles:read",
    "country_branches:read",
    "city_branches:read",
    "users:read",
    "transactions:create",
    "transactions:read",
    "transactions:post",
    "reports:read",
    "assignments:read",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "messages:create",
    "messages:read"
  ],
  staff: [
    "countries:read",
    "city_branches:read",
    "transactions:create",
    "transactions:read"
  ],
  owner: [
    "companies:read",
    "branches:read",
    "users:read",
    "users:update",
    "roles:read",
    "roles:update",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:update",
    "journal_entries:post",
    "ledger:read",
    "reports:read",
    "reports:export",
    "attachments:create",
    "attachments:read"
  ],
  accountant: [
    "branches:read",
    "accounts:read",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:update",
    "journal_entries:post",
    "ledger:read",
    "reports:read",
    "attachments:create",
    "attachments:read"
  ],
  viewer: ["branches:read", "accounts:read", "journal_entries:read", "ledger:read", "reports:read"]
} satisfies Record<string, Permission[]>;

export function hasPermission(grants: Permission[], permission: Permission) {
  return grants.includes(permission);
}
