export const enterpriseRoles = [
  "super_admin",
  "country_admin",
  "main_branch_admin",
  "city_branch_admin",
  "accountant",
  "cashier",
  "agent_user",
  "staff_user",
  "auditor_viewer"
] as const;

export type EnterpriseRole = (typeof enterpriseRoles)[number];

export const enterpriseRoleScopes: Record<EnterpriseRole, string> = {
  super_admin: "Global",
  country_admin: "Assigned country",
  main_branch_admin: "Assigned country main branch",
  city_branch_admin: "Assigned city branch",
  accountant: "Assigned accounting scope",
  cashier: "Assigned cash/payment scope",
  agent_user: "Assigned agent tasks",
  staff_user: "Assigned staff tasks",
  auditor_viewer: "Read-only assigned scope"
};

export const enterpriseRolePermissions: Record<EnterpriseRole, string[]> = {
  super_admin: [
    "companies:create",
    "companies:read",
    "companies:update",
    "business_groups:create",
    "business_groups:read",
    "business_groups:update",
    "country_company_profiles:create",
    "country_company_profiles:read",
    "country_company_profiles:update",
    "countries:create",
    "countries:read",
    "countries:update",
    "country_branches:create",
    "country_branches:read",
    "country_branches:update",
    "city_branches:create",
    "city_branches:read",
    "city_branches:update",
    "users:read",
    "users:update",
    "roles:read",
    "roles:update",
    "accounts:create",
    "accounts:read",
    "accounts:update",
    "customers:create",
    "customers:read",
    "customers:update",
    "customers:delete",
    "ledgers:create",
    "ledgers:read",
    "ledgers:update",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:update",
    "journal_entries:post",
    "roznamcha:create",
    "roznamcha:read",
    "roznamcha:update",
    "roznamcha:post",
    "approvals:create",
    "approvals:read",
    "approvals:approve",
    "reports:read",
    "reports:export",
    "currency_rates:create",
    "currency_rates:read",
    "currency_rates:update",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "products:delete",
    "product_categories:create",
    "product_categories:read",
    "product_categories:update",
    "product_brands:create",
    "product_brands:read",
    "product_brands:update",
    "product_units:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "shipping_records:update",
    "shipping_records:post",
    "clearing_agents:create",
    "clearing_agents:read",
    "clearing_agents:update",
    "clearing_agents:delete",
    "clearing_agent_branches:create",
    "clearing_agent_branches:read",
    "clearing_agent_branches:update",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "record_transfers:approve",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "inter_branch_transfers:update",
    "inter_branch_transfers:approve",
    "messages:create",
    "messages:read",
    "financial_periods:create",
    "financial_periods:read",
    "financial_periods:update",
    "settings:create",
    "settings:read",
    "settings:update",
    "modules:read",
    "audit_logs:read"
  ],
  country_admin: [
    "companies:read",
    "business_groups:read",
    "country_company_profiles:read",
    "countries:read",
    "country_branches:read",
    "city_branches:create",
    "city_branches:read",
    "city_branches:update",
    "users:read",
    "users:update",
    "customers:create",
    "customers:read",
    "customers:update",
    "ledgers:read",
    "roznamcha:read",
    "reports:read",
    "reports:export",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "shipping_records:update",
    "clearing_agents:read",
    "clearing_agent_branches:create",
    "clearing_agent_branches:read",
    "clearing_agent_branches:update",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "inter_branch_transfers:approve",
    "messages:create",
    "messages:read",
    "currency_rates:create",
    "currency_rates:read",
    "financial_periods:create",
    "financial_periods:read",
    "financial_periods:update"
  ],
  main_branch_admin: [
    "companies:read",
    "business_groups:read",
    "country_company_profiles:read",
    "countries:read",
    "country_branches:read",
    "city_branches:create",
    "city_branches:read",
    "users:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "ledgers:read",
    "financial_periods:read",
    "roznamcha:read",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "shipping_records:update",
    "clearing_agent_branches:read",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "messages:create",
    "messages:read",
    "reports:read"
  ],
  city_branch_admin: [
    "companies:read",
    "business_groups:read",
    "country_company_profiles:read",
    "city_branches:read",
    "users:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "transactions:create",
    "transactions:read",
    "roznamcha:create",
    "roznamcha:read",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "assignments:read",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "messages:create",
    "messages:read",
    "reports:read"
  ],
  accountant: [
    "companies:read",
    "accounts:create",
    "accounts:read",
    "customers:create",
    "customers:read",
    "customers:update",
    "journal_entries:create",
    "journal_entries:read",
    "journal_entries:post",
    "ledgers:read",
    "financial_periods:read",
    "purchases:create",
    "purchases:read",
    "purchases:update",
    "purchases:post",
    "products:create",
    "products:read",
    "products:update",
    "product_categories:read",
    "product_brands:read",
    "product_units:read",
    "inventory:read",
    "sales:create",
    "sales:read",
    "sales:update",
    "sales:post",
    "shipping_records:create",
    "shipping_records:read",
    "record_transfers:create",
    "record_transfers:read",
    "inter_branch_transfers:create",
    "inter_branch_transfers:read",
    "reports:read"
  ],
  cashier: ["roznamcha:create", "roznamcha:read", "transactions:create", "transactions:read", "customers:create", "customers:read"],
  agent_user: [
    "transactions:create",
    "transactions:read",
    "customers:create",
    "customers:read",
    "companies:read",
    "shipping_records:create",
    "shipping_records:read",
    "clearing_agent_branches:read",
    "assignments:create",
    "assignments:read",
    "assignments:update",
    "record_transfers:create",
    "record_transfers:read",
    "messages:create",
    "messages:read"
  ],
  staff_user: ["transactions:create", "transactions:read", "customers:read", "companies:read", "shipping_records:read"],
  auditor_viewer: ["reports:read", "audit_logs:read", "ledgers:read", "companies:read"]
};

export const dashboardByRole: Record<EnterpriseRole, string> = {
  super_admin: "/dashboard/super-admin",
  country_admin: "/dashboard/country",
  main_branch_admin: "/dashboard/main-branch",
  city_branch_admin: "/dashboard/city-branch",
  accountant: "/dashboard/city-branch",
  cashier: "/dashboard/city-branch",
  agent_user: "/dashboard/agent",
  staff_user: "/dashboard/city-branch",
  auditor_viewer: "/dashboard/reports"
};
